apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deployment
  labels:
    app: finance
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: finance-app
          image: krishnaobbu/finance:1.0  # Replace with your app image
          ports:
            - containerPort: 8081  # Application's listening port

---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: finance-service
  labels:
    app: finance
spec:
  type: NodePort  # Added service type (can be ClusterIP, NodePort, or LoadBalancer)
  selector:
    app: finance  # Must match the label in the Deployment
  ports:
    - protocol: TCP
      port: 8084       # External port
      targetPort: 8081  # The port the app inside the pod is listening on
      nodePort: 30084   # NodePort (Optional, within range 30000-32767)
